# Generated by Django 3.1 on 2020-12-26 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='企業名')),
                ('furigana', models.CharField(blank=True, max_length=50, verbose_name='フリガナ')),
                ('responsible_name', models.CharField(blank=True, max_length=50, verbose_name='担当者')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='電話番号')),
                ('fax_number', models.CharField(blank=True, max_length=12, verbose_name='FAX番号')),
                ('postal_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='住所')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='ニックネーム')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authority', to='api.authority', verbose_name='権限')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='api.department', verbose_name='部署')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザプロフィール')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('0', '窓口'), ('1', '請求'), ('2', 'その他')], default='0', max_length=2, verbose_name='支払い方法')),
                ('payment_method_other', models.CharField(blank=True, max_length=50, verbose_name='支払い方法その他')),
                ('needs_charge', models.BooleanField(default=False, verbose_name='診断書料')),
                ('exists_list', models.BooleanField(default=False, verbose_name='名簿')),
                ('exists_prior_submission_document', models.BooleanField(default=False, verbose_name='事前送付')),
                ('company_copies', models.IntegerField(default=0, verbose_name='結果送付会社')),
                ('private_copies', models.IntegerField(default=0, verbose_name='結果個人送付')),
                ('needs_to_put_grue', models.BooleanField(default=False, verbose_name='のり付け')),
                ('result_submission_method', models.CharField(choices=[('0', 'まとめて'), ('1', '月毎'), ('2', 'その他')], default='0', max_length=2, verbose_name='結果送付方法')),
                ('result_submission_method_other', models.CharField(blank=True, max_length=50, verbose_name='結果送付方法その他')),
                ('considerations', models.TextField(blank=True, verbose_name='注意事項')),
                ('related_file', models.ImageField(blank=True, upload_to='', verbose_name='関連ファイル')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='api.company', verbose_name='企業')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='api.course', verbose_name='コース')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option', to='api.option', verbose_name='オプション')),
                ('representatiove', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='担当者名')),
            ],
        ),
    ]
